"""empty message

Revision ID: 100e24a21e8c
Revises: b4edeadded25
Create Date: 2024-04-29 18:01:40.222244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100e24a21e8c'
down_revision = 'b4edeadded25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peopleId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_peopleID_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planetID_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_userID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planetId'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['peopleId'], ['id'])
        batch_op.drop_column('planetID')
        batch_op.drop_column('peopleID')
        batch_op.drop_column('userID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peopleID', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planetID', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_userID_fkey', 'user', ['userID'], ['id'])
        batch_op.create_foreign_key('favorites_planetID_fkey', 'planets', ['planetID'], ['id'])
        batch_op.create_foreign_key('favorites_peopleID_fkey', 'people', ['peopleID'], ['id'])
        batch_op.drop_column('userId')
        batch_op.drop_column('peopleId')
        batch_op.drop_column('planetId')

    # ### end Alembic commands ###
