"""empty message

Revision ID: b4edeadded25
Revises: d3874219b750
Create Date: 2024-04-28 17:37:09.962885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4edeadded25'
down_revision = 'd3874219b750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetID', sa.Integer(), nullable=True),
    sa.Column('peopleID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peopleID'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planetID'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
